### ISSUE TITLE
Only use native mozdef logging

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-it/duo_openvpn#12]
Currently the code wraps the old logging code into a mozdef msg. This has some issues as it means its not as well normalized as it could (ie it doesnt use the details.username details.ipaddress, etc fields).
In addition to that a successful duo login does not log the ip right now (it is sent and logged on the duo server though) which makes things harder to look for.

the script should instead remove CEF logging (no one uses it), and construct a mozdef msg to each "log" entry. The msg should always include client_addr and username (when known).

**Comment by gcoxmoz** [comment]
Fixed in 1.1.0.

CEF is dead and pulled.
Every log action is a MozDefEvent.
Every log is either "the code has hit trauma talking to Duo and that's our problem, it doesn't matter who the user is" or it reports the user and client IP.
